apiVersion: v1
kind: Service
metadata:
  name: mysqldb-service
  labels:
    app: mysqldb
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysqldb