apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name }}
  labels:
    app: {{ .Values.mysql.name }}
spec:
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
    spec:
      containers:
      - name: {{ .Values.mysql.name }}
        image: {{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}
        ports:
        - containerPort: {{ .Values.mysql.port }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.credentials.password | quote }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database | quote }}
        resources:
          limits:
            cpu: {{ .Values.mysql.resources.limits.cpu | quote }}
            memory: {{ .Values.mysql.resources.limits.memory | quote }}
          requests:
            cpu: {{ .Values.mysql.resources.requests.cpu | quote }}
            memory: {{ .Values.mysql.resources.requests.memory | quote }}
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: {{ .Values.mysql.pvc.name }}